### ISSUE TITLE
[EPIC]: Add Pino to Client and Server logging system and update all console.warn/log statements to server-core

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/XREngine#2799]
swap winston for pino
https://github.com/pinojs/pino

Talk to MSA and others about using this in projects

OLD NOTES

Dynamic Logging levels: none, error, warn, debug
Logging to central server. Database?

Client Logging: logging to console or pushed to server (websockets)
Server Logging: Logging to central server. Database?

Good potential lib to start with
https://github.com/winstonjs/winston

https://github.com/pimterry/loglevel
https://github.com/kutuluk/loglevel-plugin-remote

**Comment by hanzlamateen** [comment]
https://github.com/fluent/fluentd

**Comment by hanzlamateen** [comment]
https://datalust.co/seq

**Comment by HexaField** [comment]
https://www.npmjs.com/package/colors

**Comment by dmitrizagidulin** [comment]
Unless there are explicit objections from the team, we're going to do this in two stages.

### Stage 1 - Server-side logging

* [ ] Logging framework: Server side, let's use [Pino.js](https://github.com/pinojs/pino) with pluggable transports, for two main reasons. 1) it's significantly faster than Winston or loglevel (see its [benchmarks doc](https://github.com/pinojs/pino/blob/master/docs/benchmarks.md)), and 2) it's engineered to be async/multithreaded (which helps us greatly on the server side).
* [ ] Pick a log aggregator service. (such as Fluentd or ElasticSearch). Requirements: has to be open source, with the ability to self-host.

### Stage 2 - Client-side logging

* [ ] Pick and implement a client-side logging / error reporting framework that works with our log aggregator

**Comment by HexaField** [comment]
We want to also check if the client is running on the Oculus Quest, and stream the logs to a node process over Websocket
