### ISSUE TITLE
[EPIC]: DID Wallet Integration

### ISSUE THREAD

**Issue by lalalune** [XRFoundation/XREngine#3165]
Work with Dmitri to integrate the CHAPI wallet to sync user data. We will test the system by transferring data between multiple XR3ngine instances, and then across different engine types (Mozilla Hubs probably)

Spec

Specify the format of an XR Pass authentication credential.

Specify the format of the user profile (that will be stored in wallet)

Dev

Login-with-wallet feature config flag (this will control whether the ‘Login with Wallet’ button appears as an authentication option).

In addition, add ENV variables for LIFE_SERVER_CLIENT_ID, LIFE_SERVER_CLIENT_SECRET (for OAuth2 client credentials for XR3 to interface w a LS instance).

Ops

life-server needs a k8s integration

https://github.com/interop-alliance/life-server/blob/main/docs/usage-docker.md

Provision a domain for the storage server, with a subdomain for each user (that means a wildcard certificate for whatever subdomain we give it).

Set up SMTP email server on storage server (for wallet account recovery)

See also: https://github.com/XRFoundation/XREngine/issues/139

**Comment by dmitrizagidulin** [comment]
* [ ] [Generate ephemeral DID and key pair, store in cookie session](https://github.com/XRFoundation/XREngine/issues/3419)
* [ ] Expand the [did auth query / VP request object](https://github.com/XRFoundation/XREngine/blob/5cb6ab73790d89a8664b65e44a8a3853a3cc3277/packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx#L121) so that XR Engine requests the following credentials from the user's wallet:
    - The user's DID (that's the `type: 'DIDAuth'` entry)
    - a `LoginDisplayCredential`, which will contain the user's display username and avatar icon
    - a `UserPreferencesCredential` (which contains some MVP user settings)
    - a `SolidOIDC` proof of possession token that XREngine can use to read and write to the user's wallet storage.
* [ ] Extract the display name, avatar icon, and preferences, and apply them to the current session. (the name & icon part was initially implemented in PR https://github.com/XRFoundation/XREngine/pull/1709 )
* [ ] (Optionally) In case the user already had their name & icon set, prompt the user if they want to override it with the ones extracted above
* [ ] Extract the `SolidOidcCredential` and store it in the user's session. This will be used to mint PoP tokens to request data from user's wallet (such as the Contacts list)
* [ ] On the 'Update settings' screen, use a solid auth client (link tba) and the oidc credential from the previous step to write (update) the settings object on the user's wallet storage.

**Comment by shawwwwwwww** [comment]
@dmitrizagidulin great, let us know what you need to make this happen. We have skilled engineers standing  by and chomping at the bit for this :)

**Comment by dmitrizagidulin** [comment]
@shawwwwwwww awesome. Issue https://github.com/XRFoundation/XREngine/issues/3419 is ready to be assigned to someone.

**Comment by dmitrizagidulin** [comment]
Awwww yeahhhhh, here we go :)
