### ISSUE TITLE
Refactor harmony 

### ISSUE THREAD

**Issue by kimenyikevin** [XRFoundation/XREngine#4158]
## Task to be completed 

- [x]  UI/UX design (Dark theme and light theme)  on [Figma](https://www.figma.com/file/40OJwJ3vkKGHJjbfZ4XMHa/Harmony-UI?node-id=0%3A1)
- [x] Implement UI/UX in the project 
- [x] Fix chat history 
- [x] Refactor and integrate display group, party, friends, and instances 
- [x] Refactor create and send message 
- [x] Integration of inviting and receiving invites to the group 
- [x] Integration of invite and receive an invite to the party 
- [x] CRUD of group 
- [x] Integration of invite friends and receive a friend request 
- [ ] Write unit for harmony 
- [x] List group members 
- [x] update group fix 
- [x] Add to confirm the model before deleting a group 
- [x] Invite a user to group fix 
- [x]  Party menu fix 
- [x] Remove a layer from the channel 
- [x] Group or parties owner can delete, invite, edit, change user role and remove people to it. Admin can also invite people and kick them out. that we should show them a button to do it.
- [x]  Add auto-scroll to the messages and paginations
