### ISSUE TITLE
[EPIC]: Ethereal Spatial Layout & Transition Engine

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6182]
- [ ] Port spatial transition engine to bitecs, and integrate w/ XRE
- [ ] Refactor spatial layout engine
- [ ] Metaheuristic engine to bitecs
- [ ] Integrating layout engine to XREngine
