### ISSUE TITLE
[Epic]: 

### ISSUE THREAD

**Issue by dmitrizagidulin** [XRFoundation/XREngine#6453]
## Stories

* [ ] https://github.com/XRFoundation/XREngine/issues/3419
* [ ] When user logs out, clear those keys (and the solid oidc credential, below), from user session.
* [x] Expand the [did auth query / VP request object](https://github.com/XRFoundation/XREngine/blob/5cb6ab73790d89a8664b65e44a8a3853a3cc3277/packages/client-core/src/user/components/UserMenu/menus/ProfileMenu.tsx#L121) so that XR Engine requests the following credentials from the user's wallet:
    - The user's DID (that's the `type: 'DIDAuth'` entry)
    - a `LoginDisplayCredential`, which will contain the user's display username and avatar icon
    - a `UserPreferencesCredential` (which contains some MVP user settings)
    - a `SolidOIDC` proof of possession token that XREngine can use to read and write to the user's wallet storage.
* [x] Extract the display name, avatar icon, and preferences, and apply them to the current session. 
* [ ] (Optionally) In case the user already had their name & icon set, prompt the user if they want to override it with the ones extracted above
* [ ] Extract the `SolidOidcCredential` and store it in the user's session. This will be used to mint PoP tokens to request data from user's wallet (such as the Contacts list)
* [ ] On the 'Update settings' screen, use a solid auth client (link tba) and the oidc credential from the previous step to write (update) the settings object on the user's wallet storage.
