### ISSUE TITLE
[Epic]: CMS Improvements

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6706]
- [ ] #6707
- [x] #6708
- [ ] https://github.com/XRFoundation/XREngine/issues/5448
- [ ] https://github.com/XRFoundation/XREngine/issues/6155
- [ ] https://github.com/XRFoundation/XREngine/issues/7137

**Comment by HexaField** [comment]
migrated to https://github.com/XRFoundation/XREngine/issues/5448
