### ISSUE TITLE
[Epic] Spatial Recording & Playback

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#6710]
MVP
- [ ] [Story] ECS Serialization
- [ ] [Story] Basic video recording & playback with avatar 

Long term
- [ ] [Story] Remove all nullable properties from ECS scene loader components
- [ ] [Story] Refactor scene loading to be orderless
- [ ] [Story] Record network state & media streams for playback
