### ISSUE TITLE
[Epic]: Model Editor

### ISSUE THREAD

**Issue by dinomut1** [XRFoundation/XREngine#6753]
## Summary

- [x] support non entity object3d in editor hierarchy : #6636 

### Expanded Inspector + Editor
- [x] add paginated list component: #6819 
- [x] click raycast to select object3ds when model is already selected: #6808 
- [x] transform inspector for object3ds: #6808 
- [x] geometry and material inspector for meshes: #6777 #6791 
- [x] instancing transforms (+ additional buffer attributes) inspector for instanced meshes: #6819 
- [x] add toggle setting to include exploded object3d 
- [x] better nested json editor: #6818 
- [x] batch metadata editor tool: #6820 

### GLTF exporter

Implement extension serializers
- [x] DRACO compression: #6804 
- [x] meshopt compression: #6625 
- [x] meshgpu_instancing: #6754 
- [x] khr_texturebasisu: #6754 

Serverside serialization via feathers
- [x] add 'save model' button to model editor: #6754
