### ISSUE TITLE
[Epic]: Fix issues with avatars

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#7124]
A multi-part problem just surfaced in a breaking way, where the engine wouldn't load because the user's avatar wasn't in the list of avatars fetched from the API.

There were more than 100 avatars in the backend, and avatarState is only fetching 100 avatars. It seems like we need to paginate the fetch from the client side; when going through the selector, we'll need to load more once the user runs out of ones that have been loaded if there are more.

Getting the user's avatar from the large list seems inefficient. We'd have to pre-load pages until either we'd loaded every avatar in the database, or until we found the user's avatar, neither of which seems like the right solution. Maybe the user's avatar should be loaded through a separate call, so that we can be sure that it has been loaded. 

The number of avatars on dev being over 100 came from project updating/installation/etc. creating additional copies of the projects' avatars. This wasn't an issue when the avatar name was the key for an avatar, but now that it's not, whatever check is done to see if each avatar exists is never finding any matches.

It seems like we might need to have something in LoadEngineWithScene.tsx to handle if the user's avatar isn't present.

- [x] Paginate avatar fetching
- [x] Obtain the user's avatar in a more direct way
- [x] Fix projects populating their avatars more than once
- [x] Catch avatar not existing when LoadEngineWithScene.tsx spawns the user's avatar.
