### ISSUE TITLE
[Epic]: Metadata component for XR engine

### ISSUE THREAD

**Issue by SYBIOTE** [XRFoundation/XREngine#7671]
## Proposed features

- [ ] Core engine component for storing information in a dictionary format called metadata component 
- [ ] User introduced metadata for entities User interface in editor involving 
    - check box for enable disable,
    - input field/fixed text for key 
    - input field for value 
    - button to add key value pair 
    - button to remove key value pair
- [ ] Automatically link metadata of child metadata component to parent metadata component in `child` key
- [ ] Make digital beings read metadata for scene descriptions, Text- to - speech and object/ entity descriptions
